# Generated by Django 4.2.10 on 2024-03-03 20:36

import api.v1.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0002_alter_client_tag_alter_client_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                validators=[api.v1.validators.phone_number_validator],
                verbose_name="Номер телефона",
            ),
        ),
    ]
