# Generated by Django 4.2.10 on 2024-03-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0003_alter_client_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="tag",
            field=models.CharField(max_length=200, verbose_name="Тэг"),
        ),
    ]
