--
-- PostgreSQL database dump
--

-- Dumped from database version 13.14 (Debian 13.14-1.pgdg120+2)
-- Dumped by pg_dump version 13.14 (Debian 13.14-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO messenger;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO messenger;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO messenger;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO messenger;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO messenger;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO messenger;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO messenger;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO messenger;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO messenger;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO messenger;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO messenger;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO messenger;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO messenger;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO messenger;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO messenger;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO messenger;

--
-- Name: v1_client; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.v1_client (
    id bigint NOT NULL,
    phone_number character varying(11) NOT NULL,
    tag_id character varying(200) NOT NULL,
    time_zone character varying(32) NOT NULL,
    mobile_operator_id character varying(200) NOT NULL
);


ALTER TABLE public.v1_client OWNER TO messenger;

--
-- Name: v1_client_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.v1_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.v1_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: v1_mailing; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.v1_mailing (
    id bigint NOT NULL,
    start_time timestamp with time zone NOT NULL,
    stop_time timestamp with time zone NOT NULL,
    text text NOT NULL,
    tag_id character varying(200) NOT NULL,
    mobile_operator_id character varying(200) NOT NULL
);


ALTER TABLE public.v1_mailing OWNER TO messenger;

--
-- Name: v1_mailing_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.v1_mailing ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.v1_mailing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: v1_message; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.v1_message (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_sent boolean NOT NULL,
    client_id bigint NOT NULL,
    mailing_id bigint NOT NULL
);


ALTER TABLE public.v1_message OWNER TO messenger;

--
-- Name: v1_message_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.v1_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.v1_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: v1_mobileoperator; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.v1_mobileoperator (
    id bigint NOT NULL,
    code character varying(200) NOT NULL
);


ALTER TABLE public.v1_mobileoperator OWNER TO messenger;

--
-- Name: v1_mobileoperator_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.v1_mobileoperator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.v1_mobileoperator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: v1_tag; Type: TABLE; Schema: public; Owner: messenger
--

CREATE TABLE public.v1_tag (
    id bigint NOT NULL,
    name character varying(200) NOT NULL
);


ALTER TABLE public.v1_tag OWNER TO messenger;

--
-- Name: v1_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: messenger
--

ALTER TABLE public.v1_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.v1_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add crontab	7	add_crontabschedule
26	Can change crontab	7	change_crontabschedule
27	Can delete crontab	7	delete_crontabschedule
28	Can view crontab	7	view_crontabschedule
29	Can add interval	8	add_intervalschedule
30	Can change interval	8	change_intervalschedule
31	Can delete interval	8	delete_intervalschedule
32	Can view interval	8	view_intervalschedule
33	Can add periodic task	9	add_periodictask
34	Can change periodic task	9	change_periodictask
35	Can delete periodic task	9	delete_periodictask
36	Can view periodic task	9	view_periodictask
37	Can add periodic tasks	10	add_periodictasks
38	Can change periodic tasks	10	change_periodictasks
39	Can delete periodic tasks	10	delete_periodictasks
40	Can view periodic tasks	10	view_periodictasks
41	Can add solar event	11	add_solarschedule
42	Can change solar event	11	change_solarschedule
43	Can delete solar event	11	delete_solarschedule
44	Can view solar event	11	view_solarschedule
45	Can add clocked	12	add_clockedschedule
46	Can change clocked	12	change_clockedschedule
47	Can delete clocked	12	delete_clockedschedule
48	Can view clocked	12	view_clockedschedule
49	Can add Клиент	13	add_client
50	Can change Клиент	13	change_client
51	Can delete Клиент	13	delete_client
52	Can view Клиент	13	view_client
53	Can add Рассылка	14	add_mailing
54	Can change Рассылка	14	change_mailing
55	Can delete Рассылка	14	delete_mailing
56	Can view Рассылка	14	view_mailing
57	Can add mobile operator	15	add_mobileoperator
58	Can change mobile operator	15	change_mobileoperator
59	Can delete mobile operator	15	delete_mobileoperator
60	Can view mobile operator	15	view_mobileoperator
61	Can add Сообщение	16	add_message
62	Can change Сообщение	16	change_message
63	Can delete Сообщение	16	delete_message
64	Can view Сообщение	16	view_message
65	Can add tag	17	add_tag
66	Can change tag	17	change_tag
67	Can delete tag	17	delete_tag
68	Can view tag	17	view_tag
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$600000$ELoJfXADFjXRDWTFUHfzsO$h4YWcxmeozjzKUzDu6N+t8BOJjTYArdcjH/qJ1hq4mk=	2024-03-07 14:39:01.653303+00	t	admin			admin@admin.ru	t	t	2024-03-03 15:46:14.695501+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2024-03-03 15:47:25.129799+00	1	MobileOperator object (1)	1	[{"added": {}}]	15	1
2	2024-03-03 15:47:29.099036+00	2	MobileOperator object (2)	1	[{"added": {}}]	15	1
3	2024-03-03 15:47:34.111203+00	3	MobileOperator object (3)	1	[{"added": {}}]	15	1
4	2024-03-04 16:03:26.278116+00	1	2024-03-04 16:03:22+00:00	1	[{"added": {}}]	12	1
5	2024-03-04 19:16:46.608097+00	1	Mailing 8: 2023-03-04 15:52:00+00:00	3		9	1
6	2024-03-05 18:37:36.538215+00	29	Mailing object (29)	3		14	1
7	2024-03-05 18:37:36.543973+00	28	Mailing object (28)	3		14	1
8	2024-03-05 18:37:36.547657+00	27	Mailing object (27)	3		14	1
9	2024-03-05 18:37:36.551768+00	26	Mailing object (26)	3		14	1
10	2024-03-05 18:37:36.555551+00	24	Mailing object (24)	3		14	1
11	2024-03-05 18:37:36.559189+00	23	Mailing object (23)	3		14	1
12	2024-03-05 18:37:36.562323+00	22	Mailing object (22)	3		14	1
13	2024-03-05 18:37:36.566476+00	21	Mailing object (21)	3		14	1
14	2024-03-05 18:37:36.570622+00	20	Mailing object (20)	3		14	1
15	2024-03-05 18:37:36.574242+00	19	Mailing object (19)	3		14	1
16	2024-03-05 18:37:36.577837+00	18	Mailing object (18)	3		14	1
17	2024-03-05 18:37:36.580984+00	17	Mailing object (17)	3		14	1
18	2024-03-05 18:37:36.5845+00	16	Mailing object (16)	3		14	1
19	2024-03-05 18:37:36.588639+00	15	Mailing object (15)	3		14	1
20	2024-03-05 18:37:36.59176+00	14	Mailing object (14)	3		14	1
21	2024-03-05 18:37:36.59547+00	13	Mailing object (13)	3		14	1
22	2024-03-05 18:37:36.598592+00	12	Mailing object (12)	3		14	1
23	2024-03-05 18:37:36.602786+00	11	Mailing object (11)	3		14	1
24	2024-03-05 18:37:36.60643+00	10	Mailing object (10)	3		14	1
25	2024-03-05 18:37:36.610078+00	9	Mailing object (9)	3		14	1
26	2024-03-05 18:37:36.613197+00	8	Mailing object (8)	3		14	1
27	2024-03-05 18:37:36.617195+00	7	Mailing object (7)	3		14	1
28	2024-03-05 18:37:36.620803+00	6	Mailing object (6)	3		14	1
29	2024-03-05 18:37:36.62449+00	5	Mailing object (5)	3		14	1
30	2024-03-05 18:37:36.628101+00	4	Mailing object (4)	3		14	1
31	2024-03-05 18:37:36.631776+00	3	Mailing object (3)	3		14	1
32	2024-03-05 18:37:36.635071+00	1	Mailing object (1)	3		14	1
33	2024-03-05 18:37:44.887937+00	33	Mailing object (33)	3		14	1
34	2024-03-05 18:37:44.893187+00	32	Mailing object (32)	3		14	1
35	2024-03-05 18:37:44.896866+00	31	Mailing object (31)	3		14	1
36	2024-03-05 18:37:44.900599+00	30	Mailing object (30)	3		14	1
37	2024-03-05 18:38:02.470386+00	7	Client object (7)	3		13	1
38	2024-03-05 18:38:02.473506+00	6	Client object (6)	3		13	1
39	2024-03-05 18:38:02.478174+00	4	Client object (4)	3		13	1
40	2024-03-05 18:38:02.48287+00	2	Client object (2)	3		13	1
41	2024-03-05 18:38:02.486539+00	1	Client object (1)	3		13	1
42	2024-03-05 18:38:52.116072+00	7	2023-03-04 18:52:00+03:00	3		12	1
43	2024-03-05 18:38:52.120768+00	6	2023-03-04 18:52:00+03:00	3		12	1
44	2024-03-05 18:38:52.12442+00	4	2023-03-04 18:52:00+03:00	3		12	1
45	2024-03-05 18:38:52.128375+00	3	2023-03-04 18:52:00+03:00	3		12	1
46	2024-03-05 18:38:52.132079+00	2	2023-03-04 18:52:00+03:00	3		12	1
47	2024-03-05 18:38:52.135803+00	1	2024-03-04 19:03:22+03:00	3		12	1
48	2024-03-05 18:38:52.139496+00	9	2024-03-04 22:38:00+03:00	3		12	1
49	2024-03-05 18:38:52.143193+00	10	2024-03-04 22:51:00+03:00	3		12	1
50	2024-03-05 18:38:52.146665+00	11	2024-03-04 22:53:00+03:00	3		12	1
51	2024-03-05 18:38:52.150883+00	12	2024-03-04 23:04:00+03:00	3		12	1
52	2024-03-05 18:38:52.154043+00	13	2024-03-04 23:10:00+03:00	3		12	1
53	2024-03-05 18:38:52.15788+00	14	2024-03-04 23:13:00+03:00	3		12	1
54	2024-03-05 18:38:52.16211+00	15	2024-03-04 23:25:00+03:00	3		12	1
55	2024-03-05 18:38:52.165709+00	17	2024-03-04 23:26:00+03:00	3		12	1
56	2024-03-05 18:38:52.168785+00	16	2024-03-04 23:26:00+03:00	3		12	1
57	2024-03-05 18:38:52.172909+00	20	2024-03-05 00:11:00+03:00	3		12	1
58	2024-03-05 18:38:52.176088+00	19	2024-03-05 00:11:00+03:00	3		12	1
59	2024-03-05 18:38:52.180028+00	18	2024-03-05 00:11:00+03:00	3		12	1
60	2024-03-05 18:38:52.183632+00	21	2024-03-05 21:00:00+03:00	3		12	1
61	2024-03-05 18:38:52.187268+00	22	2024-03-05 21:01:00+03:00	3		12	1
62	2024-03-05 18:38:52.190959+00	25	2024-03-05 21:03:00+03:00	3		12	1
63	2024-03-05 18:38:52.194517+00	24	2024-03-05 21:03:00+03:00	3		12	1
64	2024-03-05 18:38:52.198183+00	23	2024-03-05 21:03:00+03:00	3		12	1
65	2024-03-05 18:38:52.202307+00	26	2024-03-05 21:07:00+03:00	3		12	1
66	2024-03-05 18:38:52.205943+00	30	2024-03-05 21:08:00+03:00	3		12	1
67	2024-03-05 18:38:52.208577+00	29	2024-03-05 21:08:00+03:00	3		12	1
68	2024-03-05 18:38:52.212796+00	28	2024-03-05 21:08:00+03:00	3		12	1
69	2024-03-05 18:38:52.21692+00	27	2024-03-05 21:08:00+03:00	3		12	1
70	2024-03-05 18:38:52.220565+00	31	2024-03-05 21:10:00+03:00	3		12	1
71	2024-03-05 18:38:52.224197+00	32	2024-03-05 21:21:00+03:00	3		12	1
72	2024-03-05 18:38:52.227952+00	33	2024-03-05 21:22:00+03:00	3		12	1
73	2024-03-05 18:38:52.232073+00	35	2024-03-05 21:24:00+03:00	3		12	1
74	2024-03-05 18:38:52.235673+00	34	2024-03-05 21:24:00+03:00	3		12	1
75	2024-03-05 18:38:52.239298+00	8	2025-03-04 18:52:00+03:00	3		12	1
76	2024-03-05 18:38:52.242457+00	5	2025-03-04 18:52:00+03:00	3		12	1
77	2024-03-07 14:45:55.10768+00	34	Mailing object (34)	2	[{"changed": {"fields": ["\\u0412\\u0440\\u0435\\u043c\\u044f \\u0437\\u0430\\u043f\\u0443\\u0441\\u043a\\u0430", "\\u0412\\u0440\\u0435\\u043c\\u044f \\u043e\\u043a\\u043e\\u043d\\u0447\\u0430\\u043d\\u0438\\u044f"]}}]	14	1
78	2024-03-07 15:25:36.460973+00	30	Mailing 37: 2024-03-07 18:25:00+03:00	2	[{"changed": {"fields": ["Enabled"]}}]	9	1
79	2024-03-08 16:41:36.488704+00	36	2024-03-05 22:37:00+03:00	3		12	1
80	2024-03-08 16:41:36.500003+00	37	2024-03-07 17:48:00+03:00	3		12	1
81	2024-03-08 16:41:36.503487+00	40	2024-03-07 17:50:00+03:00	3		12	1
82	2024-03-08 16:41:36.507628+00	39	2024-03-07 17:50:00+03:00	3		12	1
83	2024-03-08 16:41:36.511282+00	38	2024-03-07 17:50:00+03:00	3		12	1
84	2024-03-08 16:41:36.514891+00	41	2024-03-07 18:25:00+03:00	3		12	1
85	2024-03-08 16:41:36.51932+00	42	2024-03-07 18:27:00+03:00	3		12	1
86	2024-03-08 16:41:36.522967+00	43	2024-03-07 18:37:00+03:00	3		12	1
87	2024-03-08 16:41:36.526559+00	45	2024-03-07 18:39:00+03:00	3		12	1
88	2024-03-08 16:41:36.529681+00	44	2024-03-07 18:39:00+03:00	3		12	1
89	2024-03-08 16:41:36.533339+00	47	2024-03-07 18:41:00+03:00	3		12	1
90	2024-03-08 16:41:36.536956+00	46	2024-03-07 18:41:00+03:00	3		12	1
91	2024-03-08 16:41:36.540992+00	48	2024-03-07 18:43:00+03:00	3		12	1
92	2024-03-08 16:41:36.544567+00	49	2024-03-07 18:45:00+03:00	3		12	1
93	2024-03-08 16:41:36.548254+00	50	2024-03-07 18:46:00+03:00	3		12	1
94	2024-03-08 16:41:36.552177+00	51	2024-03-07 18:49:00+03:00	3		12	1
95	2024-03-08 16:41:36.555838+00	53	2024-03-07 18:51:00+03:00	3		12	1
96	2024-03-08 16:41:36.559399+00	52	2024-03-07 18:51:00+03:00	3		12	1
97	2024-03-08 16:41:36.563036+00	54	2024-03-07 18:53:00+03:00	3		12	1
98	2024-03-08 16:41:36.566157+00	56	2024-03-07 18:54:00+03:00	3		12	1
99	2024-03-08 16:41:36.570307+00	55	2024-03-07 18:54:00+03:00	3		12	1
100	2024-03-08 16:41:36.574453+00	57	2024-03-07 23:28:00+03:00	3		12	1
101	2024-03-08 16:41:36.578081+00	58	2024-03-08 00:18:00+03:00	3		12	1
102	2024-03-08 16:41:36.581175+00	60	2024-03-08 00:19:00+03:00	3		12	1
103	2024-03-08 16:41:36.58506+00	59	2024-03-08 00:19:00+03:00	3		12	1
104	2024-03-08 16:41:36.588737+00	61	2024-03-08 00:23:00+03:00	3		12	1
105	2024-03-08 16:41:36.591856+00	62	2024-03-08 00:30:00+03:00	3		12	1
106	2024-03-08 16:41:36.595487+00	63	2024-03-08 00:41:00+03:00	3		12	1
107	2024-03-08 16:41:36.599372+00	64	2024-03-08 00:45:00+03:00	3		12	1
108	2024-03-08 16:41:36.603138+00	65	2024-03-08 00:47:00+03:00	3		12	1
109	2024-03-08 16:41:36.606791+00	66	2024-03-08 00:50:00+03:00	3		12	1
110	2024-03-08 16:41:36.610439+00	67	2024-03-08 00:58:00+03:00	3		12	1
111	2024-03-08 16:41:36.614052+00	68	2024-03-08 01:02:00+03:00	3		12	1
112	2024-03-08 16:41:36.617975+00	69	2024-03-08 01:05:00+03:00	3		12	1
113	2024-03-08 16:41:36.621697+00	70	2024-03-08 01:09:00+03:00	3		12	1
114	2024-03-08 16:41:36.624846+00	71	2024-03-08 01:12:00+03:00	3		12	1
115	2024-03-08 16:43:10.959725+00	16	Client object (16)	1	[{"added": {}}]	13	1
116	2024-03-08 16:43:50.490448+00	52	Mailing object (52)	3		14	1
117	2024-03-08 16:43:50.495449+00	51	Mailing object (51)	3		14	1
118	2024-03-08 16:43:50.499099+00	50	Mailing object (50)	3		14	1
119	2024-03-08 16:43:50.502331+00	49	Mailing object (49)	3		14	1
120	2024-03-08 16:43:50.506836+00	48	Mailing object (48)	3		14	1
121	2024-03-08 16:43:50.510533+00	47	Mailing object (47)	3		14	1
122	2024-03-08 16:43:50.514283+00	46	Mailing object (46)	3		14	1
123	2024-03-08 16:43:50.517426+00	45	Mailing object (45)	3		14	1
124	2024-03-08 16:43:50.520975+00	44	Mailing object (44)	3		14	1
125	2024-03-08 16:43:50.524974+00	43	Mailing object (43)	3		14	1
126	2024-03-08 16:43:50.528601+00	42	Mailing object (42)	3		14	1
127	2024-03-08 16:43:50.532252+00	41	Mailing object (41)	3		14	1
128	2024-03-08 16:43:50.536053+00	40	Mailing object (40)	3		14	1
129	2024-03-08 16:43:50.540103+00	39	Mailing object (39)	3		14	1
130	2024-03-08 16:43:50.543243+00	38	Mailing object (38)	3		14	1
131	2024-03-08 16:43:50.546907+00	37	Mailing object (37)	3		14	1
132	2024-03-08 16:43:50.550572+00	36	Mailing object (36)	3		14	1
133	2024-03-08 16:43:50.553732+00	35	Mailing object (35)	3		14	1
134	2024-03-08 18:10:16.021623+00	1	A	1	[{"added": {}}]	17	1
135	2024-03-08 18:10:21.78004+00	2	B	1	[{"added": {}}]	17	1
136	2024-03-08 18:10:36.254205+00	3	C	1	[{"added": {}}]	17	1
137	2024-03-08 18:11:25.843811+00	3	admins	2	[{"changed": {"fields": ["\\u0422\\u044d\\u0433"]}}]	17	1
138	2024-03-08 18:11:25.846494+00	2	staff	2	[{"changed": {"fields": ["\\u0422\\u044d\\u0433"]}}]	17	1
139	2024-03-08 18:11:25.848897+00	1	users	2	[{"changed": {"fields": ["\\u0422\\u044d\\u0433"]}}]	17	1
140	2024-03-08 19:56:20.495+00	3	41 * * * * (m/h/dM/MY/d) UTC	3		7	1
141	2024-03-08 19:56:20.49972+00	4	43 * * * * (m/h/dM/MY/d) UTC	3		7	1
142	2024-03-08 19:57:15.757705+00	57	Mailing 64: 2024-03-08 21:20:00+03:00	3		9	1
143	2024-03-08 19:57:15.763477+00	56	Mailing 63: 2024-03-08 20:29:00+03:00	3		9	1
144	2024-03-08 19:57:15.768502+00	55	Mailing 62: 2024-03-08 20:26:00+03:00	3		9	1
145	2024-03-08 19:57:15.772062+00	54	Mailing 61: 2024-03-08 20:23:00+03:00	3		9	1
146	2024-03-08 19:57:15.775674+00	53	Mailing 60: 2024-03-08 20:16:00+03:00	3		9	1
147	2024-03-08 19:57:15.779299+00	52	Mailing 59: 2024-03-08 20:12:00+03:00	3		9	1
148	2024-03-08 19:57:15.782394+00	51	Mailing 58: 2024-03-08 20:09:00+03:00	3		9	1
149	2024-03-08 19:57:15.785949+00	50	Mailing 57: 2024-03-08 20:05:00+03:00	3		9	1
150	2024-03-08 19:57:15.789971+00	49	Mailing 56: 2024-03-08 19:57:00+03:00	3		9	1
151	2024-03-08 19:57:15.79308+00	48	Mailing 55: 2024-03-08 19:54:00+03:00	3		9	1
152	2024-03-08 19:57:15.797241+00	47	Mailing 54: 2024-03-08 19:52:00+03:00	3		9	1
153	2024-03-08 19:57:15.800443+00	46	Mailing 53: 2024-03-08 19:47:00+03:00	3		9	1
154	2024-03-08 20:07:43.9571+00	5	43 * * * * (m/h/dM/MY/d) UTC	3		7	1
155	2024-03-08 20:07:43.962388+00	6	59 * * * * (m/h/dM/MY/d) UTC	3		7	1
156	2024-03-08 20:23:21.405057+00	60	Send_info_to_email: 09 * * * * (m/h/dM/MY/d) UTC	3		9	1
157	2024-03-08 20:30:05.14189+00	61	Send_info_to_email: 25 * * * * (m/h/dM/MY/d) UTC	3		9	1
158	2024-03-08 20:40:32.550996+00	62	Send_info_to_email: 32 * * * * (m/h/dM/MY/d) UTC	3		9	1
159	2024-03-08 20:45:31.616053+00	63	Send_info_to_email: 42 * * * * (m/h/dM/MY/d) UTC	3		9	1
160	2024-03-08 20:54:41.339322+00	64	Send_info_to_email: 47 * * * * (m/h/dM/MY/d) UTC	3		9	1
161	2024-03-08 21:03:47.66258+00	65	Send_info_to_email: 56 * * * * (m/h/dM/MY/d) UTC	3		9	1
162	2024-03-09 18:43:46.385128+00	90	2024-03-09 19:30:00+03:00	3		12	1
163	2024-03-09 18:43:46.390806+00	89	2024-03-09 19:29:00+03:00	3		12	1
164	2024-03-09 18:43:46.394488+00	88	2024-03-09 19:27:00+03:00	3		12	1
165	2024-03-09 18:43:46.397562+00	87	2024-03-08 21:20:00+03:00	3		12	1
166	2024-03-09 18:43:46.400313+00	86	2024-03-08 21:20:00+03:00	3		12	1
167	2024-03-09 18:43:46.405853+00	85	2024-03-08 21:20:00+03:00	3		12	1
168	2024-03-09 18:43:46.40967+00	84	2024-03-08 21:20:00+03:00	3		12	1
169	2024-03-09 18:43:46.413307+00	83	2024-03-08 21:20:00+03:00	3		12	1
170	2024-03-09 18:43:46.416429+00	82	2024-03-08 20:29:00+03:00	3		12	1
171	2024-03-09 18:43:46.420078+00	81	2024-03-08 20:26:00+03:00	3		12	1
172	2024-03-09 18:43:46.424006+00	80	2024-03-08 20:23:00+03:00	3		12	1
173	2024-03-09 18:43:46.427616+00	79	2024-03-08 20:16:00+03:00	3		12	1
174	2024-03-09 18:43:46.430901+00	78	2024-03-08 20:12:00+03:00	3		12	1
175	2024-03-09 18:43:46.434561+00	77	2024-03-08 20:09:00+03:00	3		12	1
176	2024-03-09 18:43:46.438065+00	76	2024-03-08 20:05:00+03:00	3		12	1
177	2024-03-09 18:43:46.441685+00	75	2024-03-08 19:57:00+03:00	3		12	1
178	2024-03-09 18:43:46.445297+00	74	2024-03-08 19:54:00+03:00	3		12	1
179	2024-03-09 18:43:46.449037+00	73	2024-03-08 19:52:00+03:00	3		12	1
180	2024-03-09 18:43:46.452671+00	72	2024-03-08 19:47:00+03:00	3		12	1
181	2024-03-09 18:44:43.729612+00	15	05 * * * * (m/h/dM/MY/d) UTC	3		7	1
182	2024-03-09 18:44:43.734369+00	7	09 * * * * (m/h/dM/MY/d) UTC	3		7	1
183	2024-03-09 18:44:43.738033+00	8	11 * * * * (m/h/dM/MY/d) UTC	3		7	1
184	2024-03-09 18:44:43.739556+00	9	13 * * * * (m/h/dM/MY/d) UTC	3		7	1
185	2024-03-09 18:44:43.745296+00	10	25 * * * * (m/h/dM/MY/d) UTC	3		7	1
186	2024-03-09 18:44:43.74934+00	11	32 * * * * (m/h/dM/MY/d) UTC	3		7	1
187	2024-03-09 18:44:43.753011+00	12	42 * * * * (m/h/dM/MY/d) UTC	3		7	1
188	2024-03-09 18:44:43.756695+00	13	47 * * * * (m/h/dM/MY/d) UTC	3		7	1
189	2024-03-09 18:44:43.759836+00	14	56 * * * * (m/h/dM/MY/d) UTC	3		7	1
190	2024-03-09 18:45:31.66029+00	21	Client object (21)	3		13	1
191	2024-03-09 18:45:31.66547+00	20	Client object (20)	3		13	1
192	2024-03-09 18:45:31.669171+00	19	Client object (19)	3		13	1
193	2024-03-09 18:45:31.672843+00	18	Client object (18)	3		13	1
194	2024-03-09 18:45:31.676564+00	17	Client object (17)	3		13	1
195	2024-03-09 18:45:44.170213+00	69	Mailing object (69)	3		14	1
196	2024-03-09 18:45:44.174206+00	68	Mailing object (68)	3		14	1
197	2024-03-09 18:45:44.178235+00	67	Mailing object (67)	3		14	1
198	2024-03-09 18:45:44.181398+00	64	Mailing object (64)	3		14	1
\.


--
-- Data for Name: django_celery_beat_clockedschedule; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.django_celery_beat_clockedschedule (id, clocked_time) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_crontabschedule; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.django_celery_beat_crontabschedule (id, minute, hour, day_of_week, day_of_month, month_of_year, timezone) FROM stdin;
1	0	4	*	*	*	UTC
2	0	4	*	*	*	Europe/Moscow
\.


--
-- Data for Name: django_celery_beat_intervalschedule; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.django_celery_beat_intervalschedule (id, every, period) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictask; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.django_celery_beat_periodictask (id, name, task, args, kwargs, queue, exchange, routing_key, expires, enabled, last_run_at, total_run_count, date_changed, description, crontab_id, interval_id, solar_id, one_off, start_time, priority, headers, clocked_id, expire_seconds) FROM stdin;
2	celery.backend_cleanup	celery.backend_cleanup	[]	{}	\N	\N	\N	\N	t	\N	0	2024-03-09 16:23:40.930217+00		2	\N	\N	f	\N	\N	{}	\N	43200
\.


--
-- Data for Name: django_celery_beat_periodictasks; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.django_celery_beat_periodictasks (ident, last_update) FROM stdin;
1	2024-03-09 18:44:43.800291+00
\.


--
-- Data for Name: django_celery_beat_solarschedule; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.django_celery_beat_solarschedule (id, event, latitude, longitude) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	django_celery_beat	crontabschedule
8	django_celery_beat	intervalschedule
9	django_celery_beat	periodictask
10	django_celery_beat	periodictasks
11	django_celery_beat	solarschedule
12	django_celery_beat	clockedschedule
13	v1	client
14	v1	mailing
15	v1	mobileoperator
16	v1	message
17	v1	tag
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2024-03-03 12:35:02.718976+00
2	auth	0001_initial	2024-03-03 12:35:02.88742+00
3	admin	0001_initial	2024-03-03 12:35:02.93074+00
4	admin	0002_logentry_remove_auto_add	2024-03-03 12:35:02.942647+00
5	admin	0003_logentry_add_action_flag_choices	2024-03-03 12:35:02.954421+00
6	contenttypes	0002_remove_content_type_name	2024-03-03 12:35:02.972863+00
7	auth	0002_alter_permission_name_max_length	2024-03-03 12:35:02.985238+00
8	auth	0003_alter_user_email_max_length	2024-03-03 12:35:02.997437+00
9	auth	0004_alter_user_username_opts	2024-03-03 12:35:03.008898+00
10	auth	0005_alter_user_last_login_null	2024-03-03 12:35:03.021454+00
11	auth	0006_require_contenttypes_0002	2024-03-03 12:35:03.027818+00
12	auth	0007_alter_validators_add_error_messages	2024-03-03 12:35:03.040261+00
13	auth	0008_alter_user_username_max_length	2024-03-03 12:35:03.059567+00
14	auth	0009_alter_user_last_name_max_length	2024-03-03 12:35:03.071875+00
15	auth	0010_alter_group_name_max_length	2024-03-03 12:35:03.084889+00
16	auth	0011_update_proxy_permissions	2024-03-03 12:35:03.095969+00
17	auth	0012_alter_user_first_name_max_length	2024-03-03 12:35:03.108727+00
18	django_celery_beat	0001_initial	2024-03-03 12:35:03.187921+00
19	django_celery_beat	0002_auto_20161118_0346	2024-03-03 12:35:03.216395+00
20	django_celery_beat	0003_auto_20161209_0049	2024-03-03 12:35:03.232798+00
21	django_celery_beat	0004_auto_20170221_0000	2024-03-03 12:35:03.242442+00
22	django_celery_beat	0005_add_solarschedule_events_choices	2024-03-03 12:35:03.250549+00
23	django_celery_beat	0006_auto_20180322_0932	2024-03-03 12:35:03.283389+00
24	django_celery_beat	0007_auto_20180521_0826	2024-03-03 12:35:03.301421+00
25	django_celery_beat	0008_auto_20180914_1922	2024-03-03 12:35:03.321995+00
26	django_celery_beat	0006_auto_20180210_1226	2024-03-03 12:35:03.336709+00
27	django_celery_beat	0006_periodictask_priority	2024-03-03 12:35:03.347893+00
28	django_celery_beat	0009_periodictask_headers	2024-03-03 12:35:03.361073+00
29	django_celery_beat	0010_auto_20190429_0326	2024-03-03 12:35:03.476689+00
30	django_celery_beat	0011_auto_20190508_0153	2024-03-03 12:35:03.507975+00
31	django_celery_beat	0012_periodictask_expire_seconds	2024-03-03 12:35:03.519172+00
32	django_celery_beat	0013_auto_20200609_0727	2024-03-03 12:35:03.530905+00
33	django_celery_beat	0014_remove_clockedschedule_enabled	2024-03-03 12:35:03.541128+00
34	django_celery_beat	0015_edit_solarschedule_events_choices	2024-03-03 12:35:03.552549+00
35	django_celery_beat	0016_alter_crontabschedule_timezone	2024-03-03 12:35:03.564673+00
36	django_celery_beat	0017_alter_crontabschedule_month_of_year	2024-03-03 12:35:03.575303+00
37	django_celery_beat	0018_improve_crontab_helptext	2024-03-03 12:35:03.585471+00
38	sessions	0001_initial	2024-03-03 12:35:03.62376+00
39	v1	0001_initial	2024-03-03 15:35:39.333019+00
40	v1	0002_alter_client_tag_alter_client_time_zone	2024-03-03 19:18:45.878264+00
41	v1	0003_alter_client_phone_number	2024-03-03 20:36:12.598032+00
42	v1	0004_alter_mailing_tag	2024-03-04 12:55:13.11616+00
43	v1	0005_tag_alter_client_tag_alter_mailing_tag	2024-03-08 18:07:15.757698+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
lm0utz0ehmf7zubqm1l53wlqwsmb6f46	.eJxVjEEOwiAQRe_C2hAqbYdx6b5nIDMwSNVAUtqV8e7apAvd_vfefylP25r91mTxc1QX1anT78YUHlJ2EO9UblWHWtZlZr0r-qBNTzXK83q4fweZWv7W0LnkekpCFtCFiGYgBIxnGi0EtsAGLQuRQTeAQMDQSyLjRk4IIOr9AeyOOF0:1rgo2x:zPoYAGtndizRqgFZ9cAaZLAd_s_u_7xwZ7fZYHDcvrg	2024-03-17 15:46:39.60028+00
kznu6k1ltlf8dy8upjx6vw7pnb2ga12f	.eJxVjDsKwzAQRO-iOgitxOqTMn3OINarJXISZPCnMrl7ZHCRwFQz782uMm1rzdsicx6LuipQl99uIH5JO4bypPaYNE9tncdBH4g-10XfpyLv28n-HVRaarcNA1uDzltmLMY7h5GJvaNAAkGKSVKAIEZMERBCT3eQonhMFtXnC8sGNtU:1riEth:w57m3RbioAN7jiPlotIc9HLJV7rw651LUVGjHe66f7k	2024-03-21 14:39:01.658021+00
\.


--
-- Data for Name: v1_client; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.v1_client (id, phone_number, tag_id, time_zone, mobile_operator_id) FROM stdin;
\.


--
-- Data for Name: v1_mailing; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.v1_mailing (id, start_time, stop_time, text, tag_id, mobile_operator_id) FROM stdin;
\.


--
-- Data for Name: v1_message; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.v1_message (id, created_at, is_sent, client_id, mailing_id) FROM stdin;
\.


--
-- Data for Name: v1_mobileoperator; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.v1_mobileoperator (id, code) FROM stdin;
1	Megafon
2	MTS
3	Beeline
\.


--
-- Data for Name: v1_tag; Type: TABLE DATA; Schema: public; Owner: messenger
--

COPY public.v1_tag (id, name) FROM stdin;
3	admins
2	staff
1	users
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 198, true);


--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.django_celery_beat_clockedschedule_id_seq', 90, true);


--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.django_celery_beat_crontabschedule_id_seq', 15, true);


--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.django_celery_beat_intervalschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.django_celery_beat_periodictask_id_seq', 71, true);


--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.django_celery_beat_solarschedule_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 43, true);


--
-- Name: v1_client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.v1_client_id_seq', 25, true);


--
-- Name: v1_mailing_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.v1_mailing_id_seq', 69, true);


--
-- Name: v1_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.v1_message_id_seq', 105, true);


--
-- Name: v1_mobileoperator_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.v1_mobileoperator_id_seq', 3, true);


--
-- Name: v1_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messenger
--

SELECT pg_catalog.setval('public.v1_tag_id_seq', 3, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: v1_client v1_client_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_client
    ADD CONSTRAINT v1_client_pkey PRIMARY KEY (id);


--
-- Name: v1_mailing v1_mailing_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_mailing
    ADD CONSTRAINT v1_mailing_pkey PRIMARY KEY (id);


--
-- Name: v1_message v1_message_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_message
    ADD CONSTRAINT v1_message_pkey PRIMARY KEY (id);


--
-- Name: v1_mobileoperator v1_mobileoperator_code_key; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_mobileoperator
    ADD CONSTRAINT v1_mobileoperator_code_key UNIQUE (code);


--
-- Name: v1_mobileoperator v1_mobileoperator_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_mobileoperator
    ADD CONSTRAINT v1_mobileoperator_pkey PRIMARY KEY (id);


--
-- Name: v1_tag v1_tag_name_key; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_tag
    ADD CONSTRAINT v1_tag_name_key UNIQUE (name);


--
-- Name: v1_tag v1_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_tag
    ADD CONSTRAINT v1_tag_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: v1_client_mobile_operator_id_f6149e56; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_client_mobile_operator_id_f6149e56 ON public.v1_client USING btree (mobile_operator_id);


--
-- Name: v1_client_mobile_operator_id_f6149e56_like; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_client_mobile_operator_id_f6149e56_like ON public.v1_client USING btree (mobile_operator_id varchar_pattern_ops);


--
-- Name: v1_client_tag_id_53870f2d; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_client_tag_id_53870f2d ON public.v1_client USING btree (tag_id);


--
-- Name: v1_client_tag_id_53870f2d_like; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_client_tag_id_53870f2d_like ON public.v1_client USING btree (tag_id varchar_pattern_ops);


--
-- Name: v1_mailing_mobile_operator_id_3595cf9f; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_mailing_mobile_operator_id_3595cf9f ON public.v1_mailing USING btree (mobile_operator_id);


--
-- Name: v1_mailing_mobile_operator_id_3595cf9f_like; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_mailing_mobile_operator_id_3595cf9f_like ON public.v1_mailing USING btree (mobile_operator_id varchar_pattern_ops);


--
-- Name: v1_mailing_tag_id_a8527040; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_mailing_tag_id_a8527040 ON public.v1_mailing USING btree (tag_id);


--
-- Name: v1_mailing_tag_id_a8527040_like; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_mailing_tag_id_a8527040_like ON public.v1_mailing USING btree (tag_id varchar_pattern_ops);


--
-- Name: v1_message_client_id_96c6bc7d; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_message_client_id_96c6bc7d ON public.v1_message USING btree (client_id);


--
-- Name: v1_message_mailing_id_0c678a0d; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_message_mailing_id_0c678a0d ON public.v1_message USING btree (mailing_id);


--
-- Name: v1_mobileoperator_code_d258176f_like; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_mobileoperator_code_d258176f_like ON public.v1_mobileoperator USING btree (code varchar_pattern_ops);


--
-- Name: v1_tag_name_078c047a_like; Type: INDEX; Schema: public; Owner: messenger
--

CREATE INDEX v1_tag_name_078c047a_like ON public.v1_tag USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: v1_client v1_client_mobile_operator_id_f6149e56_fk_v1_mobileoperator_code; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_client
    ADD CONSTRAINT v1_client_mobile_operator_id_f6149e56_fk_v1_mobileoperator_code FOREIGN KEY (mobile_operator_id) REFERENCES public.v1_mobileoperator(code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: v1_client v1_client_tag_id_53870f2d_fk_v1_tag_name; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_client
    ADD CONSTRAINT v1_client_tag_id_53870f2d_fk_v1_tag_name FOREIGN KEY (tag_id) REFERENCES public.v1_tag(name) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: v1_mailing v1_mailing_mobile_operator_id_3595cf9f_fk_v1_mobile; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_mailing
    ADD CONSTRAINT v1_mailing_mobile_operator_id_3595cf9f_fk_v1_mobile FOREIGN KEY (mobile_operator_id) REFERENCES public.v1_mobileoperator(code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: v1_mailing v1_mailing_tag_id_a8527040_fk_v1_tag_name; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_mailing
    ADD CONSTRAINT v1_mailing_tag_id_a8527040_fk_v1_tag_name FOREIGN KEY (tag_id) REFERENCES public.v1_tag(name) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: v1_message v1_message_client_id_96c6bc7d_fk_v1_client_id; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_message
    ADD CONSTRAINT v1_message_client_id_96c6bc7d_fk_v1_client_id FOREIGN KEY (client_id) REFERENCES public.v1_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: v1_message v1_message_mailing_id_0c678a0d_fk_v1_mailing_id; Type: FK CONSTRAINT; Schema: public; Owner: messenger
--

ALTER TABLE ONLY public.v1_message
    ADD CONSTRAINT v1_message_mailing_id_0c678a0d_fk_v1_mailing_id FOREIGN KEY (mailing_id) REFERENCES public.v1_mailing(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

